#!/bin/bash

BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "${BASEDIR}"

rm -f ASDFfile

asdf_plugins=($(asdf plugin list))
for plugin in ${asdf_plugins[@]}; do
    echo $plugin $(asdf list $plugin) >> ASDFfile
done
