#!/bin/bash

BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

TEMP_DIR=$(mktemp -d)
cd $TEMP_DIR


function cleanup {
    cd $BASEDIR
    rm -rf "$TEMP_DIR"
}


while read line; do
    icon_url=${line##* }
    app_path=${line% *}
    icon_path=$(curl --silent --write-out "%{filename_effective}" -O "$icon_url")
    sudo fileicon set "$app_path" "$icon_path"
done < $BASEDIR/Iconsfile

trap cleanup EXIT

sudo killall Finder
